### ISSUE TITLE
Footer Disappears when scrolling listbuttons(only)

### ISSUE THREAD

**Issue by putztzu** [watusi/jquery-mobile-iscrollview#15]
The original content without any scrolling plugin can be viewed as a reference as how the content should look
http://3horn.us/sdiego/index.html

Wrapping only the listbuttons, the footer has disappeared.  Am also observing the issue mentioned in the notes that describes the scrollbar extending in length beside both the banner and listbuttons despite wrapping only the listbuttons.
http://3horn.us/sdiego/index3.html

Tested on Android 2.3.4 and desktop Chrome, believe this behavior would be the same on other devices as well.

Great stuff if this works.

Thx,
TS

**Comment by jtara** [comment]
Please add data-iscroll-foreground class to your content div that has the banner, and let me know if that fixes it.
That tells the widget to subtract the height of that div from the wrapper height.

Alternately, you can just put the banner in an additional data-role="header" div. This is what I tend to do for this sort of thing.

Scrollbar issue is fixed in 1.2. Just working on the documentation update.

**Comment by putztzu** [comment]
Tried
1. Wrap the banner in its own "header" div. No effect except to fix the scrollbar issue (as expected the scrollbar only extends the length of the listview buttons)
1. Added class="data-iscroll-foreground" to the banner div, no effect.

Tested in desktop Chrome, I usually do this before deploying for mobile device testing.

In both these cases the footer is still missing altogether. To my eye, most likely the display's vertical sizing is not being calculated properly, my guess is that some arbitrary and/or default value is being used.

TS

**Comment by jtara** [comment]
The class needs to be "iscroll-foreground" not "data-iscroll-foreground". Sorry for the error above.

Multiple data-role="header" divs should work as well, though. I use this in my own app. I have a page that has a traditional header, and below that a search bar containing a form.

Not sure if it's OK to have multiple data-role="content" divs.

**Comment by putztzu** [comment]
Have deployed your suggestion to add class="iscroll-foreground" to the banner image and removed the data-role="content" attribute, can be viewed at
http://3horn.us/sdiego/index4.html

The listview scrolls, but the footer is not rendered when viewed on Android 2.3.4.
When viewed in desktop Chrome, interestingly the vertical dimension does not seem to be calculated accurately. I would normally expect that however the Chrome window is re-sized, the footer vertical dimension should be re-calculated and the footer rendered visibly. Instead, it looks like the vertical dimension is fixed, so you will see both the windows scrollbar and the iscroll scrollbar inside. You will see the footer only if you scroll the window scrollbar, the iscroll scrollbar as expected will not reveal the footer.

So, assuming that the problem observed in desktop Chrome also exists when viewed in a mobile device, I believe it explains why the footer is not visible (the vertical dimension is not calculated dynamically, is fixed so the footer is offscreen).

I believe the only characteristic that's unique/different about my footer is that it contains a linkbutton whereas you deploy a navbar with blocks... Could that be some kind of clue?

TS

**Comment by putztzu** [comment]
Playing around with window re-sizing a bit more on the desktop, it looks to me like the vertical size calculation may be off approx (maybe exactly?) the height of the banner.

I've seen suggestions to modify using a z-index value, but in those situations I think it's normally a positive value whereas in this situation it might be a negative value? I wonder if a negative z-index value is even valid?

Am investigating...
TS

**Comment by jtara** [comment]
Yes, negative Z-indices are valid.

However, with 1.2 I am removing the use of Z-index, since the scroller position bug has been fixed. There doesn't seem to be any reason any more to set Z-indices.

**Comment by jtara** [comment]
Wrapper height issues should be fixed in 1.2. Please let me know if this is still a problem, and I will re-open.

**Comment by mgm8870** [comment]
This still seems to occur for me.

**Comment by jtara** [comment]
mem8870: can you please supply more details? Browser? Device? Browser version? When does it occur? Always? Sometimes? What happens when you change device orientation? Is this occurring with the demo, or with your own page? If with your own page, please supply an example.

If this is still occurring, would you mind opening a new issue with the details?

Thanks.
